# Generated by Django 3.1.7 on 2021-04-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
